### ISSUE TITLE
how to widen the priority colour band at the side of tasks

### ISSUE THREAD

**Issue by DiGwork** [projectfork/Projectfork#1555]
Hi My client is not that good at destinguishing between the priorities in list view and would like the colour bands widened. How do I go about doing that?

**Comment by eaxs** [comment]
You can override it with CSS. The default css is:

```css
.priority-1 {border-left:2px solid #CCC;}
.priority-2 {border-left:2px solid #468847;}
.priority-3 {border-left:2px solid #3a87ad;}
.priority-4 {border-left:2px solid #c09853;}
.priority-5 {border-left:2px solid #b94a48;}
```

I suggest you override it through your template's css file, or add a new file entirely. Also, if your changes dont seem to take effect, add `!important` to force it, like this:
```css
.priority-1 {border-left:4px solid #CCC !important;}
```
