### ISSUE TITLE
How to change the colour and tick box icon in front of task in list

### ISSUE THREAD

**Issue by DiGwork** [projectfork/Projectfork#1556]
My client is not so good at differentiating between the greyed out (done) tasks and the live tasks.
Is the a way to set the colour to something more obvious than grey?

Is the a way to get the tick box Icon to be an empty box for unticked tasks while ticked tasks showw the ticked box?

**Comment by eaxs** [comment]
The css for completed tasks is:
```css
.complete .task-title > a, .complete .task-description, .complete .caret
{
    opacity:0.35;
}
```
It's changing opacity rather than color. You can remove this entirely (by setting opacity to 1) and replace it with something else, as described in #1555

**Comment by DiGwork** [comment]
I just cannot seem to find this In the template CSS to be able to edit:
.complete .task-title > a, .complete .task-description, .complete .caret
{
    opacity:0.35;
}

**Comment by eaxs** [comment]
It's not part of the template.css, but rather hardcoded into the layout :(
But you can override it by force using `!important`:

```css
.complete .task-title > a, .complete .task-description, .complete .caret
{
opacity:1 !important;
/* More styles here */
}
```
