### ISSUE TITLE
How can I make the Emerald Template Sidebar hidden by default?

### ISSUE THREAD

**Issue by BrenDude** [projectfork/Projectfork#1625]
I'm using the Emerald Template and would like it to be full screen most of the time in desktop full screen size.  I noticed that when the sreeen is resized (like for mobile devices) the sidebar is hidden by default.  How can I make the Emerald Template Sidebar hidden by default on all screen sizes?
Thanks in advance.

**Comment by eaxs** [comment]
Unfortunately this is not configurable. But you can add a new CSS file or modify an existing and add this code:
```css
.navbar-fixed-top
{
    margin-left: 0px;
    left: 0px;
}
#content,
#sidebar 
{
    margin-left: 0px;
}
```
